-- Post service schema: posts + engagement (likes, comments).
-- One database per service; ids are UUIDs generated by the app. Usernames are
-- denormalised onto each row so events carry them (event-carried state) without
-- calling user-service.

CREATE TABLE posts (
    id              UUID PRIMARY KEY,
    author_id       UUID        NOT NULL,
    author_username TEXT        NOT NULL,
    caption         TEXT,
    image_url       TEXT        NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL
);

CREATE TABLE likes (
    id         UUID PRIMARY KEY,
    post_id    UUID        NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    user_id    UUID        NOT NULL,
    username   TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (post_id, user_id)          -- a user can like a post at most once
);

CREATE TABLE comments (
    id         UUID PRIMARY KEY,
    post_id    UUID        NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    user_id    UUID        NOT NULL,
    username   TEXT        NOT NULL,
    text       TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_posts_author     ON posts (author_id);
CREATE INDEX idx_posts_created_at ON posts (created_at DESC);
CREATE INDEX idx_likes_post       ON likes (post_id);
CREATE INDEX idx_comments_post    ON comments (post_id);
